modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://gitlab.com/groups/modding-legacy/-/issues"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
[[mods]]
	modId="dungeons_plus"
	version="${file.jarVersion}"
	displayName="Dungeons Plus"
	displayURL="https://moddinglegacy.com/"
	logoFile="logo.png"
	authors="Silver_David"
	description='''Adds a few new dungeons to the world using Structure Gel API'''
[[dependencies.dungeons_plus]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dungeons_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.dungeons_plus]]
    modId="structure_gel"
    mandatory=true
    versionRange="[1.7.0,]"
    ordering="NONE"
    side="BOTH"