modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://gitlab.com/groups/modding-legacy/-/issues"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
[[mods]]
	modId="dungeons_plus"
	version="${file.jarVersion}"
	displayName="Dungeons Plus"
	displayURL="https://moddinglegacy.com/"
	logoFile="logo.png"
	credits="KingPhygieBoo"
	authors="Silver_David"
	description='''Adds a few new dungeons to the world using Structure Gel API'''
[[dependencies.dungeons_plus]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dungeons_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dungeons_plus]]
    modId="structure_gel"
    mandatory=true
    versionRange="[2.8.0,]"
    ordering="NONE"
    side="BOTH"