modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://gitlab.com/groups/modding-legacy/-/issues"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
[[mods]]
	modId="dungeons_plus"
	version="${file.jarVersion}"
	displayName="Dungeons Plus"
	displayURL="https://moddinglegacy.com/"
	logoFile="logo.png"
	credits="KingPhygieBoo"
	authors="Silver_David"
	description='''Adds a few new dungeons to the world using Structure Gel API'''
[[dependencies.dungeons_plus]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dungeons_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19]"
    ordering="NONE"
    side="BOTH"
[[dependencies.dungeons_plus]]
    modId="structure_gel"
    mandatory=true
    versionRange="[2.4.5,]"
    ordering="NONE"
    side="BOTH"