modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://gitlab.com/groups/modding-legacy/-/issues"
[[mods]]
	modId="dungeons_plus"
	version="${file.jarVersion}"
	displayName="Dungeons Plus"
	displayURL="https://moddinglegacy.com/"
	logoFile="logo.png"
	authors="Silver_David"
	description='''Adds a few new dungeons to the world using Structure Gel API'''
[[dependencies.dungeons_plus]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.7,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dungeons_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.dungeons_plus]]
    modId="structure_gel"
    mandatory=true
    versionRange="[1.1.0,]"
    ordering="NONE"
    side="BOTH"